import type { SportType } from '@/types/sport'

// Apple HealthKit (snake_case, e.g. "running") and Google Health Connect
// (UPPERCASE, e.g. "TRAIL_RUN") workout types → OpenStride SportType.
// Normalising the input to UPPER_SNAKE merges both vocabularies into one table.
// Ported from Open Wearables' apple_sdk / google exercise-type maps.
const HEALTH_SPORT_MAP: Record<string, SportType> = {
  // Running
  RUNNING: 'running',
  INCLINE_RUN: 'running',
  VIRTUAL_RUN: 'running',
  TRAIL_RUN: 'trail_running',
  TRAIL_RUNNING: 'trail_running',
  TREADMILL: 'treadmill_running',
  TREADMILL_RUNNING: 'treadmill_running',
  // Walking & hiking
  WALKING: 'walking',
  INCLINE_WALK: 'walking',
  NORDIC_WALKING: 'walking',
  STROLLER_WALK: 'walking',
  POWER_WALKING: 'walking',
  WALK_WITH_WEIGHTS: 'walking',
  TREADMILL_WALK: 'walking',
  WHEELCHAIR_WALK: 'walking',
  WHEELCHAIR_RUN: 'running',
  HIKING: 'hiking',
  RUCKING: 'hiking',
  BACKPACKING: 'hiking',
  // Cycling
  CYCLING: 'cycling',
  BIKING: 'cycling',
  OUTDOOR_BIKE: 'cycling',
  HAND_CYCLING: 'cycling',
  UNICYCLING: 'cycling',
  MOUNTAIN_BIKE: 'mountain_biking',
  MOUNTAIN_BIKING: 'mountain_biking',
  STATIONARY_BIKE: 'indoor_cycling',
  ASSAULT_BIKE: 'indoor_cycling',
  SPINNING: 'indoor_cycling',
  ELECTRIC_BIKE: 'e_biking',
  // Swimming & water
  SWIMMING: 'swimming',
  SWIMMING_POOL: 'pool_swimming',
  LAP_SWIMMING: 'pool_swimming',
  SWIMMING_OPEN_WATER: 'open_water_swimming',
  OPEN_WATER_SWIMMING: 'open_water_swimming',
  ROWING: 'rowing',
  ROWING_MACHINE: 'rowing_machine',
  KAYAKING: 'kayaking',
  CANOEING: 'canoeing',
  PADDLEBOARDING: 'stand_up_paddleboarding',
  PADDLE_SPORTS: 'paddling',
  SURFING: 'surfing',
  SURFING_SPORTS: 'surfing',
  KITESURFING: 'kitesurfing',
  WINDSURFING: 'windsurfing',
  SAILING: 'sailing',
  WAKEBOARDING: 'wakeboarding',
  WATER_SKIING: 'water_skiing',
  WATER_POLO: 'water_sports',
  WATER_SPORT: 'water_sports',
  WATER_SPORTS: 'water_sports',
  WATER_FITNESS: 'water_sports',
  FISHING: 'fishing',
  // Gym & fitness
  STRENGTH_TRAINING: 'strength_training',
  TRADITIONAL_STRENGTH_TRAINING: 'strength_training',
  FUNCTIONAL_STRENGTH_TRAINING: 'strength_training',
  CORE_TRAINING: 'strength_training',
  BODY_WEIGHT: 'strength_training',
  CALISTHENICS: 'strength_training',
  POWERLIFTING: 'strength_training',
  WEIGHTLIFTING: 'strength_training',
  WEIGHTS: 'strength_training',
  CROSSFIT: 'strength_training',
  ELLIPTICAL: 'elliptical',
  STAIRCLIMBER: 'stair_climbing',
  STAIR_CLIMBING: 'stair_climbing',
  STAIRS: 'stair_climbing',
  STEP_TRAINING: 'stair_climbing',
  JUMP_ROPE: 'cardio_training',
  JUMPING_ROPE: 'cardio_training',
  // Cardio & class formats
  AEROBIC_WORKOUT: 'cardio_training',
  CARDIO_WORKOUT: 'cardio_training',
  HIIT: 'cardio_training',
  TABATA_WORKOUT: 'cardio_training',
  INTERVAL_WORKOUT: 'cardio_training',
  CIRCUIT_TRAINING: 'cardio_training',
  CROSS_TRAINING: 'cardio_training',
  MIXED_CARDIO: 'cardio_training',
  BOOTCAMP: 'cardio_training',
  FITNESS_GAMING: 'cardio_training',
  // Flexibility & mind-body
  YOGA: 'yoga',
  YOGA_BIKRAM: 'yoga',
  YOGA_HATHA: 'yoga',
  PILATES: 'pilates',
  BARRE: 'stretching',
  FLEXIBILITY: 'stretching',
  STRETCHING: 'stretching',
  COOLDOWN: 'stretching',
  PREPARATION_AND_RECOVERY: 'stretching',
  MIND_AND_BODY: 'stretching',
  MEDITATION: 'stretching',
  // Dance
  DANCE: 'dance',
  CARDIO_DANCE: 'dance',
  SOCIAL_DANCE: 'dance',
  DANCING: 'dance',
  // Team sports
  AMERICAN_FOOTBALL: 'american_football',
  BASEBALL: 'baseball',
  SOFTBALL: 'baseball',
  BASKETBALL: 'basketball',
  CRICKET: 'cricket',
  HOCKEY: 'hockey',
  ICE_HOCKEY: 'hockey',
  FIELD_HOCKEY: 'hockey',
  HANDBALL: 'team_sports',
  LACROSSE: 'lacrosse',
  RUGBY: 'rugby',
  SOCCER: 'soccer',
  FOOTBALL: 'soccer',
  VOLLEYBALL: 'volleyball',
  DISC_SPORTS: 'disc_sports',
  FRISBEE: 'disc_sports',
  // Racket sports
  BADMINTON: 'badminton',
  PICKLEBALL: 'pickleball',
  RACQUETBALL: 'racquetball',
  SQUASH: 'squash',
  TABLE_TENNIS: 'table_tennis',
  TENNIS: 'tennis',
  // Winter
  CROSS_COUNTRY_SKIING: 'cross_country_skiing',
  DOWNHILL_SKIING: 'alpine_skiing',
  ALPINE_SKIING: 'alpine_skiing',
  SKIING: 'skiing',
  SNOW_SPORTS: 'winter_sports',
  SNOWBOARDING: 'snowboarding',
  SNOWSHOEING: 'snowshoeing',
  ICE_SKATING: 'ice_skating',
  SKATING: 'ice_skating',
  CURLING: 'winter_sports',
  // Outdoor & other
  CLIMBING: 'rock_climbing',
  ROCK_CLIMBING: 'rock_climbing',
  BOULDERING: 'indoor_climbing',
  GOLF: 'golf',
  BOXING: 'boxing',
  KICKBOXING: 'boxing',
  MARTIAL_ARTS: 'martial_arts',
  SKATEBOARDING: 'skateboarding',
  INLINE_SKATING: 'inline_skating',
  WHEELCHAIR: 'wheelchair'
}

/** Map an Apple HealthKit / Health Connect workout type string to a SportType. */
export function mapHealthSport(workoutType: unknown): SportType {
  if (typeof workoutType !== 'string' || !workoutType) return 'other'
  const key = workoutType
    .replace(/^HKWorkoutActivityType/i, '')
    .toUpperCase()
    .replace(/[\s-]+/g, '_')
  return HEALTH_SPORT_MAP[key] ?? 'other'
}
